# START GENAI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app.kubernetes.io/name: backend
    # El label de versión se sobreescribe en el overlay
    app.kubernetes.io/version: "1.2.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app.kubernetes.io/version: "1.2.0"
    spec:
      containers:
      - name: nginx
        image: nginx:1.25   # tag reemplazado por overlay
        ports:
        - containerPort: 80

# END GENAI