
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/stdedwin-git/poc-version-trace   # <- Windows usa / o \
    targetRevision: main
    path: base
    kustomize: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

