# START GENAI
resources:
  - ../../base

# Cambiar imágenes y tags
images:
  - name: nginx
    newTag: "1.26"
  - name: python
    newTag: "3.11-alpine"
  - name: postgres
    newTag: "15.4-alpine"

# Añadir/actualizar el label de versión
patches:
  - path: version-frontend.yaml
  - path: version-backend.yaml
  - path: version-db.yaml

# END GENAI