# START GENAI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: v15.4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app.kubernetes.io/version: v15.4

# END GENAI